### ISSUE TITLE
Population grows beyond N

### ISSUE THREAD

**Issue by moepmoep12** [m4saka/xxr#12]
The population in XCSR grows beyond the defined maximum number N.

		auto constants = xxr::XCSRConstants();
		constants.n = 700;
		std::unordered_set<int> options = std::unordered_set<int>{ 1, 2,3 };
		m_xcsr = new xxr::XCSR<>(xxr::CSR, options, constants);

**Comment by m4saka** [comment]
Thank you for your report.

I have checked the sum of numerosity in population with several environments, but it didn't exceed N.

- XCSR (N=700) with 6-bit Real multiplexer problem:
```
iteration    reward    popsize  numerositysum     step
     5000   600.800    382.140        575.129    1.000
    10000   680.400    501.097        700.000    1.000
    15000   865.000    417.066        700.000    1.000
    20000   969.600    369.568        700.000    1.000
```

- XCSR (N=700) with Checkerboard problem (2x2):
```
iteration    reward    popsize  numerositysum     step
     5000   812.400    137.693        521.186    1.000
    10000   983.400     61.783        700.000    1.000
    15000   982.200     62.831        700.000    1.000
    20000   983.000     72.443        700.000    1.000
```

- XCSR (N=5000) with 11-bit Real multiplexer problem:
```
iteration    reward    popsize  numerositysum     step
     5000   573.800   1392.191       1903.707    1.000
    10000   564.400   3304.456       4385.887    1.000
    15000   584.600   3973.248       5000.000    1.000
    20000   618.600   4069.221       5000.000    1.000
    25000   621.000   4110.010       5000.000    1.000
    30000   646.200   4096.326       5000.000    1.000
    35000   681.600   4073.895       5000.000    1.000
    40000   705.600   3985.766       5000.000    1.000
    45000   742.600   3883.768       5000.000    1.000
    50000   764.600   3737.607       5000.000    1.000
```

I confirmed these with the last commit a58ab60 of master branch by adding the sum of numerosity to the summary output.

And I have also checked with your fork (https://github.com/moepmoep12/xxr), but the sum of numerosity never exceeded N.
(But your fork is not up-to-date and does not contain a recent commit c6862f914ab2af9e87a1de1f3a47db6f9bfbb7fd, the limit of numerosity sum has been N-1 instead of N.)

This issue is not reproduced.
Could you provide a working code or more information in detail?

**Comment by moepmoep12** [comment]
Thank you for your quick response. 

Indeed, your latest commit did solve the problem. The numerosity sum is now constant.
